### PR TITLE
resolve() is not pin()

### PR DESCRIPTION
**Pull request by cboettig**
It is often desirable to write R scripts that start with some command about where to get data from some online URL.  But because downloading data is slow, it's often nice to cache a local copy (particularly if you will re-run the script frequently).  This can be done manually with a bit of extra R of course (e.g. `if(!file.exists(my_data)) download.file(url, my_data)`) but is cumbersome.  

`pins::pin()` takes a URL, downloads a copy to local cache and promises only to re-download the object at that URL if the eTag has changed. (If there's no eTag I'm not clear what it does)

We can achieve something similar with `contenturi`, but it is different in important ways.  First, we'd register the URL,

```r
 url <- paste0("https://data.giss.nasa.gov/gistemp/graphs/graph_data/",
                       "Global_Mean_Estimates_based_on_Land_and_Ocean_Data/graph.txt")
register(url)
```
which returns an id:

```r
hash://sha256/ce1865032089bec8e8a5b0b572c2cb2e3e89bfa8b824520136232d286a908f86"
```

Now we use the id in our code, instead of the URL:

```r
my_file <- resolve("hash://sha256/ce1865032089bec8e8a5b0b572c2cb2e3e89bfa8b824520136232d286a908f86", store = TRUE)
```

`store = TRUE` part will cache a local copy if one does not already exist.  

So, why bother?  Is  this just a more ugly complicated version of pins?  Perhaps, but it has several advantages too:

- Reproducibility.  If the resource at the URL changes, the code fails
- Robustness.  If the content moves to another URL, we do not have to update our code.  We can merely register the new URL.  (Or if another user registers another URL for the same content, we can automatically get that URL from the public registry!)

### CODE REVIEW

**Comment by jhpoelen** [comment]
Nice! Good to know that ```pin()``` relies on registry/store provided eTags (usually encoded content hashes) to check whether content changed. While using eTags is a fast way to check whether content might have changed, it does require the requestor to trust the content providers and the communication channel. With your proposed ```resolve()``` neither the eTag nor the trust is required, because resolve first queries a registry by a content uri, then gets the bits 'n bytes and verifies whether the content uri hasn't changes by calculating the content uri again. To avoid having a (potentially) expensive and unreliable (things might change) operation like a data download, a local copy is kept. 

And, assuming that the local content store and local provenance store (aka registry) keep the origin/source of the content, you can do a ```query("hash://sha256/ce1865032089bec8e8a5b0b572c2cb2e3e89bfa8b824520136232d286a908f86")``` against the local provenance store to learn more about the context (e.g., url , date) the data came from. 

Some notes on implementation:

I read: 
```R
my_file <- resolve("hash://sha256/ce18650...", store = TRUE)
```

as:

```R
# a remote store as configured by a single data url: any retrieve() on this store would return the content from that one resource location
store_remote <- init_remote_url_store("https://example.org/data.zip", should_verify=TRUE)
# local stores are configured by some base path
store_local <- init_local_store("~/.contenturi", should_verify=FALSE)
my_file <- resolve("hash://sha256/ce18650...", list(store_local, store_remote))
```

With this store list approach, you can chain all sorts of stores to implement the pull-through cache that you are proposing. This is similar to the ```default_registries()``` configuration that is already present in the ```resolve()``` implementation.

Note that remote stores with base urls and naming conventions can also be imagined, so that a endpoint like:

```https://deeplinker.bio/```

would result in retrieving bits 'n bytes from  ```https://deeplinker.bio/29d30b566f924355a383b13cd48c3aa239d42cba0a55f4ccfc2930289b88b43c``` when invoking the ```retrieve("hash://sha256/29d30b566f924355a383b13cd48c3aa239d42cba0a55f4ccfc2930289b88b43c")``` method.

**Comment by cboettig** [comment]
Yes! this is great.  

Is it possible to get/query a `registry` from http://deeplinker.bio store? Minimally this could merely be a list of all content URIs or shasums.  (Alternatively we can obviously manually make a curl header request or something to see if a given content uri can be found in deeplinker.bio).

**Comment by jhpoelen** [comment]
@cboettig definitely possible. Would you want to include related URL as well as DOIs ?

**Comment by cboettig** [comment]
Thanks!  URLs that purport to hold the content registered are immediately useful (since that acts like a "url store" like hash-archive.org -- though I think preston has already registered those urls with hash-archive.org as well redundancy is nice).  

DOIs and additional provenance are of course interesting, but I don't see a functions like `resolve()` using that information.  (I'm starting to work through my thinking/implementations on the metadata / prov side of things now, but I see that as a layer that goes on top of contenturi, rather than a sub-component of contenturi...)

**Comment by jhpoelen** [comment]
Here's the one liner to get all the urls <> content hashes for GBIF, iDigBio, BioCASe:

```
$ preston ls -l tsv --remote https://deeplinker.bio/ | grep hasVersion | cut -f1,3 
https://search.idigbio.org/v2/search/publishers	hash://sha256/3eff98d4b66368fd8d1f8fa1af6a057774d8a407a4771490beeb9e7add76f362
https://api.gbif.org/v1/dataset	hash://sha256/184886cc6ae4490a49a70b6fd9a3e1dfafce433fc8e3d022c89e0b75ea3cda0b
https://bms.gfbio.org/services/data-sources/	hash://sha256/ba4f1de1f97ef57c90d321b7bf36426ac4031fa3a312af2c22a538d0f4387a4c
http://tb.plazi.org/GgServer/dwca/0C0BAB28FF8CFFA7FF83B2699D17FFAE.zip	hash://sha256/8799c41e5d54fdc1ed07fbf30b9d5f67d2f30ff1ffa7430da9c043084e617c48
http://ipt.museums.or.ke/ipt/archive.do?r=asfmammals	hash://sha256/f8d5cb453ba8a9b709e9f9a676430d7577e11881dba5284873320ef735c269b0
```

Different remotes can be use for optimal speed or different provenance logs (e.g., DataONE, BHL).

Here's the first 10 in a table: 

url | contenturi
-- | --
https://search.idigbio.org/v2/search/publishers | hash://sha256/3eff98d4b66368fd8d1f8fa1af6a057774d8a407a4771490beeb9e7add76f362
https://api.gbif.org/v1/dataset | hash://sha256/184886cc6ae4490a49a70b6fd9a3e1dfafce433fc8e3d022c89e0b75ea3cda0b
https://bms.gfbio.org/services/data-sources/ | hash://sha256/ba4f1de1f97ef57c90d321b7bf36426ac4031fa3a312af2c22a538d0f4387a4c
http://tb.plazi.org/GgServer/dwca/0C0BAB28FF8CFFA7FF83B2699D17FFAE.zip | hash://sha256/8799c41e5d54fdc1ed07fbf30b9d5f67d2f30ff1ffa7430da9c043084e617c48
http://ipt.museums.or.ke/ipt/archive.do?r=asfmammals | hash://sha256/f8d5cb453ba8a9b709e9f9a676430d7577e11881dba5284873320ef735c269b0
http://ipt.museums.or.ke/ipt/eml.do?r=asfmammals | hash://sha256/e0a12b591ddf6c10f932200def417990278edf78ba822966cc6b3e7b195a4118
http://ipt.gbifbenin.org/archive.do?r=cnsf_niger | hash://sha256/d981008d7c7dddd827bcba16087a9c88cf233567d4751f67bb7f96e0756f2c9c
http://ipt.gbifbenin.org/eml.do?r=cnsf_niger | hash://sha256/737c2e27b74286757c75f8215c677b16bbc5ab0dc1f1028e22cb9d186593f332
http://ipt.tacc.utexas.edu/archive.do?r=tnhci | hash://sha256/a5c078686c6dc575b141a7476f299618a2199c1f098b28a0c9c99c531b00f431
http://ipt.tacc.utexas.edu/eml.do?r=tnhci | hash://sha256/2c03651ef6a7c6bed0e672ee8fd481fbf02417c3868aca646fb86841ef577559


@cboettig what would be a good way to distributed this lookup table?

**Comment by cboettig** [comment]
@jhpoelen thanks for this, that's really awesome.  

I dunno what's really best, but `tsv.gz` seems like a very practical format that would be easy for most tools & users to work with efficiently.  Perhaps it would make more sense to distribute as nquads, but I'm concerned that adds considerable friction, so I really like how `preston` supports the `tsv` export.  Just ran this and looks like I get ~114 MB `.tsv.gz` [file](https://hash-archive.org/sources/hash://sha256/86df0d24994a34dfc5e638f8b378c1b6d52ff1a051c12d93aa04984c15bf9624)

**Comment by jhpoelen** [comment]
Nice! Great to see that data.carlboettiger.info is back . . . and glad to hear that you like to pragmatism of the tsv export. (ps thelio as in system76's thelio?)

**Comment by cboettig** [comment]
yup! Thelio is indeed a system76 thelio we got for the lab recently, and will hopefully act as the more long-lived host for data.carlboettiger.info (particularly now that i have a better idea how to use a content-addressed store).   The data storage is just backed by 2 5TB spinning harddrives in a mirrored `zpool` at the moment so we'll see how far that gets me...  but meanwhile I'm pretty happy to finally own a hardware host system and no longer be entirely dependent on renewing allocations for various cloud services.  (and I bought my first system76 laptop in 2007 so always glad to work with them!)

**Comment by cboettig** [comment]
@jhpoelen minor weirdness here, but I'm seeing something funny with the `tsv` I get back from preston when I try to read it in with `readr` library in R.  `readr` complains that the [file](https://hash-archive.org/sources/hash://sha256/86df0d24994a34dfc5e638f8b378c1b6d52ff1a051c12d93aa04984c15bf9624) has an invalid multibyte string.  (I just created it with a `>` redirect from the preston command above).  

The base R functions, e.g. `read.table()`, handle this file just fine -- I don't think they do the multibyte string file type detection stuff that `readr` does.  Any thoughts?

**Comment by jhpoelen** [comment]
What is the text encoding you are using? UTF-8? Also, do you have specific info on the offending line?

**Comment by cboettig** [comment]
never mind on the encoding, it just seems that `readr::read_tsv()` is actually just failing if I don't have the `.tsv.gz` file extension on the name.  I don't see why that should be the case, but just an aside I do keep on running into workflows that require their input file names aren't changed.  I know this can be handled as additional metadata, but it has been a bit of reminder how dependent we can be on file names.

**Comment by jhpoelen** [comment]
@cboettig  thanks for letting me know - I was wondering why that encoding issue happened . . . There's some neat projects that guess content type from the content itself: Apache Tika (https://tika.apache.org). Alternatively, the data context (aka provenance) might help to provide hints to what the content should be.  For now, I imagine that hardcoding the assumptions might be a pragmatic way forward ; )

**Pull request merged**
